# Generated by Django 6.0.4 on 2026-05-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stundent',
            new_name='Student',
        ),
    ]
